### ISSUE TITLE
Working only for Python 3.x codes

### ISSUE THREAD

**Issue by rosafilgueira** [rosafilgueira/code_inspector#39]
If the repository to inspect uses a Python version bellow 3.x, such as [zhiqiangdon/CU-Net](https://github.com/zhiqiangdon/CU-Net) (Python 2.7), the "ast module" is not able to work properly if we have a Python 3.X environment (which is what is necessary to run code_inspector) . 

code_inspector manages the error, but obviously is not able to parser some files, such as the ones that uses "old printing style" (e.g. _print 'save prefix: ', checkpoint.save_prefix_ (Line 76) --> [zhiqiangdon/CU-Net/cu-net.py](https://github.com/zhiqiangdon/CU-Net/blob/master/cu-net.py)). 

**The issue is that  "ast module" can only handle Python code for the version of Python it is shipped with**.

So, I have tested if creating a **Python 2.7 environment**, would solve this issue. However, code_inspector comes with 2 libraries (cdmcfparser and docstring_parser), which dont have support anymore for Python 2.7.  So, code_inspector does not run in a Python 2.7 environment. 

Something to have in mind!

**Comment by dgarijo** [comment]
I am in favor of placing a warning stating that we work for 3.x + and that's it :)

**Comment by rosafilgueira** [comment]
Agreed!

**Comment by rosafilgueira** [comment]
Closing the issue then!
